modLoader="javafml"
loaderVersion="[4,)"
issueTrackerURL="https://github.com/Mrbysco/DiscCord/issues"
license="MIT"

[[mods]]
modId="disccord"
version="${file.jarVersion}"
displayName="DiscCord"
displayURL="https://www.curseforge.com/minecraft/mc-mods/DiscCord"
authors="Mrbysco"
description='''
A mod that allows you to write music URLs on a Custom Record to play in a Jukebox
'''
[[dependencies.disccord]]
modId="minecraft"
type="REQUIRED"
versionRange="[1.21,1.22)"
ordering="NONE"
side="BOTH"
[[dependencies.disccord]]
modId="neoforge"
type="required"
versionRange="[21.1.0,)"
ordering="NONE"
side="BOTH"
[[dependencies.disccord]]
modId="sophisticatedcore"
type="optional"
versionRange="[1.3.20,)"
ordering="NONE"
side="BOTH"
[[mixins]]
config="disccord.mixins.json"
[[mixins]]
config="disccord.compat.mixins.json"